import './assets/main.css'
import './assets/styles/stitch-colors.css'

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faSearch,
  faPlus,
  faClipboard,
  faChevronLeft,
  faChevronRight,
  faTrash,
  faCheckCircle,
  faCircle,
  faArrowLeft,
  faArrowRight,
  faUser,
  faSave,
  faSignOutAlt,
  faUserCircle,
  faEnvelope,
  faLock,
  faSignInAlt,
  faUserPlus,
  faSun,
  faMoon,
  faFlask,
  faToggleOn,
  faToggleOff,
  faMagic,
  faHistory,
  faChartLine,
  faCode,
  faStickyNote,
  faTimes,
  faChartPie,
  faFont,
  faPalette,
  faShapes,
  faBars,
  faHome,
  faFolder,
  faPencilRuler,
  faStore,
  faTools,
  faInfoCircle,
  faThLarge,
  faList,
  faTh,
  faCalendarAlt,
  faTrashAlt,
  faFileExport,
  faFileImport,
  faChartBar,
  faArchive,
  faFolderOpen,
  // Adding missing icons
  faCamera,
  faShieldAlt,
  faEye,
  faEyeSlash,
  faKey,
  faSlidersH,
  faBell,
  faCog,
  faDownload,
  faExclamationCircle,
  faExclamationTriangle,
  faDatabase,
  faEdit,
  faDonate,
  faSearchPlus,
  faSearchMinus,
  faCloudArrowUp
} from '@fortawesome/free-solid-svg-icons'

// Add icons to the library
library.add(
  faSearch,
  faPlus,
  faClipboard,
  faChevronLeft,
  faChevronRight,
  faTrash,
  faCheckCircle,
  faCircle,
  faArrowLeft,
  faArrowRight,
  faUser,
  faSave,
  faSignOutAlt,
  faUserCircle,
  faEnvelope,
  faLock,
  faSignInAlt,
  faUserPlus,
  faSun,
  faMoon,
  faFlask,
  faToggleOn,
  faToggleOff,
  faMagic,
  faHistory,
  faChartLine,
  faCode,
  faStickyNote,
  faTimes,
  faChartPie,
  faFont,
  faPalette,
  faShapes,
  faBars,
  faHome,
  faFolder,
  faPencilRuler,
  faStore,
  faTools,
  faInfoCircle,
  faThLarge,
  faList,
  faTh,
  faCalendarAlt,
  faTrashAlt,
  faFileExport,
  faFileImport,
  faChartBar,
  faArchive,
  faFolderOpen,
  // Adding missing icons
  faCamera,
  faShieldAlt,
  faEye,
  faEyeSlash,
  faKey,
  faSlidersH,
  faBell,
  faCog,
  faDownload,
  faExclamationCircle,
  faExclamationTriangle,
  faDatabase,
  faEdit,
  faDonate,
  faSearchPlus,
  faSearchMinus,
  faCloudArrowUp
)

const app = createApp(App)
const pinia = createPinia()

app.component('font-awesome-icon', FontAwesomeIcon)
app.use(pinia)
app.use(router)

app.mount('#app')
